name: CI for release tags

on:
  push:
    tags:
      - "v*"

jobs:
  once:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Checkout repository recursively
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Set package metadata
        id: meta
        shell: bash
        run: |
          echo ::set-output name=NAME::sdsl-c-template
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
        
      - name: Build release archive
        id: build_release_archive
        run: |
          ./${{ github.workspace }}/build_release.sh ${{ steps.meta.outputs.NAME }} ${{ steps.meta.outputs.VERSION }}

      - name: Upload release archive
        id: upload_archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/build/release_archive/${{ steps.meta.outputs.NAME }}-${{ steps.meta.outputs.VERSION }}.zip
          asset_name: ${{ steps.meta.outputs.NAME }}-${{ steps.meta.outputs.VERSION }}.zip
          asset_content_type: application/octet-stream
